# Generated by Django 5.1.3 on 2024-11-15 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('server_ip_address', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyAPI.bankserver')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BANK', 'Bank Transfer'), ('MOBILE', 'Mobile Money Transfer')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_iban', models.CharField(blank=True, max_length=34, null=True)),
                ('target_swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('target_bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('target_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('target_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('target_country', models.CharField(blank=True, max_length=50, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='MoneyAPI.bankaccount')),
            ],
        ),
    ]
