# Generated by Django 5.1.3 on 2024-11-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='Pending', max_length=20),
        ),
    ]
